var tek = require('tek'),
    file = tek.file,
    fs = require('fs'),
    path = require('path'),
    resolve = path.resolve,
    config = require('../app.config'),
    JobQueue = tek.meta['JobQueue'];

function handleErr(err) {
    console.error(err);
}
module.exports = function (filename, namespace, data, callback) {
    try {
        var filepath = resolve(config.jsDir, filename);

        var content = [
            "/** auto generated by u.publish.js **/\n",
            [namespace, '=', ''].join(' '),
            JSON.stringify(data, null, 4),
            [';'].join(' ')
        ].join('');

        fs.writeFile(filepath, content, function (err) {
            err && handleErr(err);
            console.log('published locale file:', filepath);
            callback && callback();
        });
    } catch (e) {
        handleErr(e);
    }
};